### ISSUE TITLE
is it possible to instantiate multiple Elevators classes, using the same elevator.hpp and .cpp?

### ISSUE THREAD

**Issue by husnaini798** [digint/tinyfsm#35] opened 2022-07-04 07:38 UTC
is it possible to instantiate multiple Elevators classes, using the same elevator.hpp and .cpp? if so, how?

Thanks

**Comment by digint** [comment] 2022-07-04 19:28
duplicate of #3

**Closed as completed by digint** 2022-07-04 19:28 UTC
Labels: duplicate

**Comment by husnaini798** [comment] 2022-07-04 23:05
Hi Alex,
Thanks for your reply. The multiple switches make sense at compile time.

But how do I declare all those 'defectiveswitches' at runtime?

FSM_INITIAL_STATE(DefectiveSwitch<2>, Off<2> )

I would like to use this for a warning system (and based on the user input
the warnings will move to different states). However, at the start I
wouldn't know how many warnings would I recieve. I could recieve 1000s or
more warnings as the system runs/continues or none at all.

Appreciate your help with this.

Thanks.

Kind regards,
Husnain Malik

**Comment by husnaini798** [comment] 2022-07-05 01:35
Or,
If somehow I wrap the state machine's struct/class (i.e. warning),
struct warning : tinyfsm::fsm<warning>
, in another class 'like MyWarning'

And then create multiple instances of MyWarning class. Would that create
multiple MyWarnings, each containing a seperate tinyfsm's 'warning state
machine'?

Or since everything is static, multiple Mywarning instances would all be
using one tinyfsm's warning state machine?

Thanks
